[package]
name = "HeadsOrTails"
version = "1.1"
edition = "10 nov. 2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
throbber = "0.1.4"
